spring:
  datasource:
    url: jdbc:mysql://localhost:3306/gestionstock?createDatabaseIfNotExist=true&userSSL=false&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  ## Specify DBMS
  jpa:
    database: MYSQL
    show-sql: false
    properties:
      hibernate:
        session_factory:
          interceptor: com.example.spring.interceptor.Interceptor

    # Hibernate DDL Auto (create, create-drop, update)
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQL5Dialect

server:
  port: 8081

flickr:
  apiKey: 49eefa0b16579badfef2363101aa25ec
  apiSecret: 3a0c4705e4e96cb1
  appKey: 72157720822870416-7c9332dd4e8e3e93
  appSecret: 3c2fd4d539a16cb7
